services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calories-api-container
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: calories-frontend-container
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000/predict
    depends_on:
      - api
